"""
JSON Schemas for org-agenda-api endpoints.

This module provides JSON Schema definitions for validating API responses.
"""

from .definitions import DEFINITIONS
from .endpoints import (
    GET_ALL_TODOS_RESPONSE,
    AGENDA_RESPONSE,
    CAPTURE_TEMPLATES_RESPONSE,
    CAPTURE_REQUEST,
    CAPTURE_RESPONSE,
    HEALTH_RESPONSE,
    VERSION_RESPONSE,
    TODO_STATES_RESPONSE,
    FILTER_OPTIONS_RESPONSE,
    AGENDA_FILES_RESPONSE,
    CUSTOM_VIEWS_RESPONSE,
    CUSTOM_VIEW_RESPONSE,
    METADATA_RESPONSE,
    UPDATE_REQUEST,
    UPDATE_RESPONSE,
    COMPLETE_REQUEST,
    COMPLETE_RESPONSE,
    DELETE_REQUEST,
    DELETE_RESPONSE,
    CATEGORY_TYPES_RESPONSE,
    CATEGORIES_RESPONSE,
    CATEGORY_TASKS_RESPONSE,
    CATEGORY_CAPTURE_REQUEST,
    HABIT_STATUS_RESPONSE,
)

__all__ = [
    "DEFINITIONS",
    "GET_ALL_TODOS_RESPONSE",
    "AGENDA_RESPONSE",
    "CAPTURE_TEMPLATES_RESPONSE",
    "CAPTURE_REQUEST",
    "CAPTURE_RESPONSE",
    "HEALTH_RESPONSE",
    "VERSION_RESPONSE",
    "TODO_STATES_RESPONSE",
    "FILTER_OPTIONS_RESPONSE",
    "AGENDA_FILES_RESPONSE",
    "CUSTOM_VIEWS_RESPONSE",
    "CUSTOM_VIEW_RESPONSE",
    "METADATA_RESPONSE",
    "UPDATE_REQUEST",
    "UPDATE_RESPONSE",
    "COMPLETE_REQUEST",
    "COMPLETE_RESPONSE",
    "DELETE_REQUEST",
    "DELETE_RESPONSE",
    "CATEGORY_TYPES_RESPONSE",
    "CATEGORIES_RESPONSE",
    "CATEGORY_TASKS_RESPONSE",
    "CATEGORY_CAPTURE_REQUEST",
    "HABIT_STATUS_RESPONSE",
]
